### PR TITLE
refactored for Jest tests

### PR DESCRIPTION
**Pull request by nadchif**
I refactored the code for Jest unit tests. Submitting this as PR so you can review easily and share your thoughts/feedback before merging to development

### CODE REVIEW

**Review by michaeldera — APPROVED** [review]
Looks good to me, however I did not actually do a test on my local machine.

**Review by michaeldera — CHANGES_REQUESTED** [review]
You deleted the licence, may you add that back?

**Comment by michaeldera** [comment]
> Looks good to me, however I did not actually do a test on my local machine.

With regards to packaging, we are still doing that the same way?

**Review by michaeldera — APPROVED** [review]

**Review by michaeldera — APPROVED** [review]

**Comment by nadchif** [comment]
> You deleted the licence, may you add that back?

I am sorry 🙈  . Moments like this i am happy  I went with a Pull Request + Review request. Thank you for bringing that to my attention

**Comment by michaeldera** [comment]
All good. Thank you again. I will try and finish my commitments on the backend.

**Comment by nadchif** [comment]
once again, a pleasure 🙏

**Pull request merged**
