### PR TITLE
fixes extension fetching issue

### LINKED ISSUE #2: Reading Data from Readable Stream
**Describe the bug**
When I call the REST endpoint that is supposed to receive the JSON payload with the content of the image, I get a Readable Stream object in the response body (`response.body`), I am not having the best time trying to read the stream. 

**To Reproduce**
1. Clone the repo and and set up the extension in developer mode as inidcated in the [contributing guidelines](https://github.com/michaeldera/image-accessibility-extension/blob/master/CONTRIBUTING.md)
2. Active the extension and add a debugger (`debugger;`) on the response from `fetch`;
4. Inspection of the `response.body` after reloading a page with an image without alt atttributes will indicate it is a readable stream

**Expected behavior**
Would like to either be able to read the stream or to receive the response as a JSON payload (Worth mentioning that tools such as Swagger, Insomnia, Postman receive the reponse as JSON)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge (Chromium)
 - Version 81.0.416.68 (Official build) (64-bit)

### PR DESCRIPTION
**Pull request by nadchif**
This fixes https://github.com/michaeldera/image-accessibility-extension/issues/2 by using a background extension script to handle fetching the response from your API. The reason why it was getting blocked on chrome was because of the CORS and CORB policies. This is the recommended way to get around that.

See also: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

### CODE REVIEW

**Review by michaeldera — APPROVED** [review]
Yes, your fault-finding is spot-on. I was at a point where I knew waht the problem was but was not sure yet how to solve it. You are getting that repsonse because I was using a key that expired for the backend but the problem is certainly addressed now.

**Comment by nadchif** [comment]
@michaeldera Thank you, you had really done all the heavy lifting already 🙌  

This is a really great extension 💡 I love where you are headed

**Comment by michaeldera** [comment]
Awesome! I changed environment variables in the api if you would like to see your efforts actually working.... It allows a couple of hundred of requests per minute for now 🚀

**Comment by nadchif** [comment]
oooh man!!!! This is so coool 👏 👏 Well done! 

If ever you need collaborators, please count me in!

**Comment by michaeldera** [comment]
Awesome. Likewise mate!  I will just keep adding issues for all the ideas I have... even the ones up for discussion then we can continue working on it.

**Pull request merged**
